In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv(r'D:\Resume Classification System\data\raw\Dataset.csv')
df1.head()

   Unnamed: 0    Category                                               Text
0           0  Accountant  ﻿________________\r\n\r\nEDUCATION\r\nOMBA - E...
1           1  Accountant  ﻿________________\r\n\r\nHOWARD GERRARD\r\nAcc...
2           2  Accountant  ﻿________________\r\n\r\nKevin Frank\r\nSENIOR...
3           3  Accountant  ﻿________________\r\n\r\nPlace of birth\r\nNat...
4           4  Accountant  ﻿________________\r\n\r\nStephen Greet, CPA\r\...

In [3]:
df1 = df1.drop('Unnamed: 0',axis=1)

In [4]:
df1.head()

     Category                                               Text
0  Accountant  ﻿________________\r\n\r\nEDUCATION\r\nOMBA - E...
1  Accountant  ﻿________________\r\n\r\nHOWARD GERRARD\r\nAcc...
2  Accountant  ﻿________________\r\n\r\nKevin Frank\r\nSENIOR...
3  Accountant  ﻿________________\r\n\r\nPlace of birth\r\nNat...
4  Accountant  ﻿________________\r\n\r\nStephen Greet, CPA\r\...

In [5]:
df2 = pd.read_csv(r'D:\Resume Classification System\data\raw\github_categorized.csv')
df2.head()

   Unnamed: 0      Category                                               Text
0           0   AI Engineer  Abhishek kumar\nartificial intelligence and ma...
1           2  Data Analyst  DATA ANALYST F/H\n\nArailym PERNEBAY\n\nperneb...
2           3  Data Analyst  # CV 4: Cybersecurity Analyst\n**Name**: Emily...
3           4  Data Analyst  Name: Ravi Kumar\nContact: ravi.k@email.com | ...
4           5  Data Analyst  Title: Top Analyst Reports for Bank of America...

In [6]:
df2 = df2.drop('Unnamed: 0',axis=1)

In [7]:
df2.head()

       Category                                               Text
0   AI Engineer  Abhishek kumar\nartificial intelligence and ma...
1  Data Analyst  DATA ANALYST F/H\n\nArailym PERNEBAY\n\nperneb...
2  Data Analyst  # CV 4: Cybersecurity Analyst\n**Name**: Emily...
3  Data Analyst  Name: Ravi Kumar\nContact: ravi.k@email.com | ...
4  Data Analyst  Title: Top Analyst Reports for Bank of America...

In [8]:
df3 = pd.read_csv(r'D:\Resume Classification System\data\raw\synthetic_dataset.csv')
df3.head()

   Unnamed: 0     Category                                               Text
0           0  AI Engineer  Name: Eleanor Vance\n\nSummary:\nHighly motiva...
1           1  AI Engineer  JOHN SMITH\n(123) 456-7890 | john.smith@email....
2           2  AI Engineer  [Name] Anya Sharma\n[Phone] (555) 123-4567\n[E...
3           3  AI Engineer  Jane Doe\n(123) 456-7890 | jane.doe@email.com ...
4           4  AI Engineer  Jane Doe\n(123) 456-7890 | jane.doe@email.com ...

In [9]:
df3 = df3.drop("Unnamed: 0",axis=1)

In [10]:
df3.head()

      Category                                               Text
0  AI Engineer  Name: Eleanor Vance\n\nSummary:\nHighly motiva...
1  AI Engineer  JOHN SMITH\n(123) 456-7890 | john.smith@email....
2  AI Engineer  [Name] Anya Sharma\n[Phone] (555) 123-4567\n[E...
3  AI Engineer  Jane Doe\n(123) 456-7890 | jane.doe@email.com ...
4  AI Engineer  Jane Doe\n(123) 456-7890 | jane.doe@email.com ...

In [11]:
print(df1.columns)
print(df2.columns)
print(df3.columns)

Index(['Category', 'Text'], dtype='object')
Index(['Category', 'Text'], dtype='object')
Index(['Category', 'Text'], dtype='object')

In [12]:
print(df1['Category'].unique())
print(df2['Category'].unique())
print(df3['Category'].unique())

['Accountant' 'Advocate' 'Agriculture' 'Apparel' 'Architecture' 'Arts'
 'Automobile' 'Aviation' 'Banking' 'Blockchain' 'BPO'
 'Building and Construction' 'Business Analyst' 'Civil Engineer'
 'Consultant' 'Data Scientist' 'Database' 'Designing' 'DevOps'
 'Digital Media' 'DotNet Developer' 'Education' 'Electrical Engineering'
 'ETL Developer' 'Finance' 'Food and Beverages' 'Health and Fitness'
 'Human Resources' 'Information Technology' 'Java Developer' 'Management'
 'Mechanical Engineer' 'Network Security Engineer' 'Operations Manager'
 'PMO' 'Public Relations' 'Python Developer' 'React Developer' 'Sales'
 'SAP Developer' 'SQL Developer' 'Testing' 'Web Designing']
['AI Engineer' 'Data Analyst' 'Data Scientist' 'ML Engineer']
['AI Engineer' 'Computer Vision Engineer' 'Data Analyst' 'Data Engineer'
 'NLP Engineer']

In [13]:
print(df1.dtypes)
print(df2.dtypes)
print(df3.dtypes)

Category    object
Text        object
dtype: object
Category    object
Text        object
dtype: object
Category    object
Text        object
dtype: object

In [14]:
df1_shuffled = df1.sample(frac=1, random_state=42).reset_index(drop=True)
df2_shuffled = df2.sample(frac=1, random_state=42).reset_index(drop=True)
df3_shuffled = df3.sample(frac=1, random_state=42).reset_index(drop=True)

In [15]:
combined_df = pd.concat([df1_shuffled, df2_shuffled, df3_shuffled], ignore_index=True)

In [16]:
final_shuffled_df = combined_df.sample(frac=1).reset_index(drop=True)

In [17]:
final_shuffled_df.head()

           Category                                               Text
0  DotNet Developer  ﻿________________\r\n\r\nJESSICA CLAIRE\r\nMon...
1           Banking  ﻿________________\r\n\r\nJESSICA CLAIRE\r\nres...
2      Architecture  ﻿________________\r\n\r\nJESSICA CLAIRE\r\n100...
3            DevOps  ﻿________________\r\n\r\nASSOCIATE DEVOPS ENGI...
4  Public Relations  ﻿________________\r\n\r\nPROFESSIONAL SUMMARY\...

In [18]:
final_shuffled_df.tail()

,Category,Text
14030,Digital Media,﻿________________\r\n\r\nMARKETING COORDINATOR...
14031,Operations Manager,﻿________________\r\n\r\nJESSICA CLAIRE\r\nres...
14032,Business Analyst,﻿________________\r\n\r\nJordan Kirtley\r\nBus...
14033,Public Relations,﻿________________\r\n\r\nJESSICA CLAIRE\r\nMon...
14034,Electrical Engineering,﻿________________\r\n\r\nDarron Emmerich\r\n54...

In [ ]:
final_shuffled_df.to_csv(r'D:\Resume Classification System\data\processed\Combined_Data.csv')